# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod properties
mod.name=Animatium
mod.id=animatium
mod.version=3.0
mod.group=org.visuals.legacy
mod.description=Visual Tweaks/QOL Settings For Modern Minecraft Versions, Aimed At 1.7/1.8 players.
mod.source=https://github.com/Legacy-Visuals-Project/Animatium/
mod.issues=https://github.com/Legacy-Visuals-Project/Animatium/issues
mod.license=GPL-3.0-with-linking-exception
mod.modrinth=https://modrinth.com/mod/animatium/
mod.curseforge=http://legacy.curseforge.com/minecraft/mc-mods/animatium
mod.discord=https://discord.gg/C8KKgbA8jy
mod.development=false

# Publishing
publish.modrinth=
publish.curseforge=

# Dependencies
deps.fabric_loader_version=0.17.3
deps.devauth_version=1.2.2
deps.lombok_version=1.18.42
deps.mixinconstraints_version=1.1.0
deps.mixinsquared_version=0.2.0

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.mc_dep=1.21.1
mod.mc_version=1.21.1

# Versioned
deps.parchment_version=2024.07.28
deps.fabric_api_version=0.102.1+1.21.1
deps.neoforge_version=21.1.1
