[versions]
minecraft = "1.21.1"
fabric-api = "0.102.1+1.21.1"
yarn = "1.21.1+build.3"
fabric-loader = "0.16.10"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
loom = { id = "dev.architectury.loom", version.ref = "loom" }
publishing = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publishing" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
fletchingtable-fabric = { id = "dev.kikugie.fletching-table.fabric", version.ref = "fletchingtable" }
